name: campus_assistant
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.0.0

  # Notifications (local – Android/iOS only)
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # Local storage
  shared_preferences: ^2.2.2

  # HTTP client for API integration
  http: ^1.2.1

  # Date formatting
  intl: ^0.19.0

  # Calendar widget
  table_calendar: ^3.0.9

  # Lab 11 – Option D: Data Visualization
  fl_chart: ^0.68.0

  # Lab 11 – Option B: Image / Media Upload
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/profile.jpg
